[tools]
uv = "latest"

[tasks.ruff]
description = "Run ruff linter"
run = "ruff check ."
hide = true

[tasks.mypy]
description = "Run mypy linter"
run = "mypy ."
hide = true

[tasks.pyright]
description = "Run basedpyright linter"
run = "basedpyright ."
hide = true

[tasks.check-format]
description = "Check if code is formatted"
run = "ruff format --check"

[tasks.lint]
description = "Run linters"
run = [
    { tasks = [ 'ruff', 'mypy', 'pyright' ] },
]

[tasks.test]
description = "Run tests"
run = "pytest ."

[tasks.check]
description = "Run linters and tests"
run = [
    { task = 'check-format' },
    { task = 'lint' },
    { task = 'test' }
]

[tasks.clean]
description = "Clean the project"
run = """
#!/usr/bin/env bash
uv clean
find . -type d -name "*cache" -exec rm -r {} +
find . -type d -name "__pycache__" -exec rm -rf {} + && find . -name "*.pyc" -delete
"""

[settings]
python.uv_venv_auto = "create|source"
